USE [master]
GO

/****** Object:  Database [dbAxia]    Script Date: 06/08/2022 19:36:11 ******/
CREATE DATABASE [dbAxia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbAxia', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbAxia.mdf' , SIZE = 43008KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbAxia_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbAxia_log.ldf' , SIZE = 3136KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbAxia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbAxia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbAxia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbAxia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbAxia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbAxia] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbAxia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbAxia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbAxia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbAxia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbAxia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbAxia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbAxia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbAxia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbAxia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbAxia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbAxia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbAxia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbAxia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbAxia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbAxia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbAxia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbAxia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbAxia] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbAxia] SET  MULTI_USER 
GO

ALTER DATABASE [dbAxia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbAxia] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbAxia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbAxia] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbAxia] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbAxia] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbAxia] SET  READ_WRITE 
GO

